
sever:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url : jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  output:
    ANSI:
      enabled: ALWAYS
  h2:
  console:
    enabled : true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - "qa"
  config:
    import:  "optional:configserver:http://localhost:8071"
#  To disable this check, set spring.cloud.config.enabled=false or
#  spring.cloud.config.import-check.enabled=false.
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"

#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"