services:
  configserver:
    image: "amudeyan/configserver:s9"
    container_name: configserver_ms
    ports:
      - "8071:8071"
#      - "8072:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amudeyan
  eurekaserver:
    image: "amudeyan/eurekaserver:s9"
    container_name: eurekaserver_ms
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "8070:8070"
    #      - "8081:8080"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amudeyan
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default

  accounts:
    image: "amudeyan/accounts:s9"
    container_name : accounts_ms
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "8080:8080"
#      - "8081:8080"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory : 700m
    networks:
      - amudeyan
    environment:
      SPRING_APPLICATION_NAME : "accounts"
      SPRING_CONFIG_IMPORT : "configserver:http://configserver:8071/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
      SPRING_PROFILES_ACTIVE: default

  cards:
    image: "amudeyan/cards:s9"
    container_name: cards_ms
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "9000:9000"
#      - "9001:9000"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amudeyan
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
      SPRING_PROFILES_ACTIVE: default
  loans:
    image: "amudeyan/loans:s9"
    container_name: loans_ms
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "8090:8090"
#      - "8091:8090"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amudeyan
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
      SPRING_PROFILES_ACTIVE: default
  apigateway:
    image: "amudeyan/apigateway:s9"
    container_name: apigateway_ms
    ports:
      - "8072:8072"
    #      - "8091:8090"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amudeyan
    environment:
      SPRING_APPLICATION_NAME: "apigateway"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
      SPRING_PROFILES_ACTIVE: default
networks:
  amudeyan:
    driver: "bridge"