#spring.application.name=microservices
sever:
  port=8081
spring:
  datasource:
    url : jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  output:
    ANSI:
      enabled: ALWAYS
  h2:
  console:
    enabled : true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
