spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

loans:
  name: "application:loans in prod Profile"
  contactDetails:
    email: "amudeyan.k"
    phone : "+91 6372839392"
  landLine:
    - "(33) 43 454"
    -  "(33) 43 454"