services:
  accounts:
    image: "amudeyan/accounts:s4"
    container_name : accounts_ms
    ports:
      - "8080:8080"
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory : 700m
    networks:
      - amudeyan
  cards:
    image: "amudeyan/cards:s4"
    container_name: cards_ms
    ports:
      - "9000:9000"
      - "9001:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amudeyan
  loans:
    image: "amudeyan/loans:s4"
    container_name: loans_ms
    ports:
      - "8090:8090"
      - "8091:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amudeyan
networks:
  amudeyan:
    driver: "bridge"