server:
  port: 9070
spring:
  application:
    name: "eurekaservertwo"
  config:
    import: "optional:configserver:http://localhost:8071"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled : true
    liveness-state:
      enabled : true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  server:
    enableReplication: true
    enable-self-preservation: false
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
     defaultZone: http://localhost:8070/eureka/
