
sever:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url : jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  output:
    ANSI:
      enabled: always
  h2:
    console:
      enabled : true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

  profiles:
    active:
      - "qa"
  config:
    import:  "optional:configserver:http://localhost:8071"
#  To disable this check, set spring.cloud.config.enabled=false or
#  spring.cloud.config.import-check.enabled=false.
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled:
        true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"
logging:
  level:
    com:
      eazybytes:
        microservices: debug

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
resilience4j.retry:
  instances:
    default:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
#      retryExceptions:
#        - org.springframework.web.client.HttpServerErrorException
#        - java.io.IOException
#        - java.lang.RuntimeException
#      ignoreExceptions:
#        - io.github.robwin.exception.BusinessException

#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"