server:
    port: 9000
spring:
    application:
        name: "cards"
    datasource:
        url: jdbc:mysql://localhost:3307/cardsdb
        username: root
        password: root
    jpa:
        show-sql: true
    sql:
        init:
            mode: always
    config:
        import: "optional:configserver:http://localhost:8071/"

    profiles:
        active: "prod"
management:
    endpoints:
        web:
            exposure:
                include: "*"
#rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"