spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
server:
  port: 8071
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
management:
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"

#decrypt:
#  key: "45D81EC1EF61DF9AD8D3E5BB397F9"